### ISSUE TITLE
go.sum file could be deleted

### ISSUE THREAD

**Issue by beaquant** [sdcoffey/techan#17]
go.sum file is generated by golang with go.mod automatically.

**Comment by sdcoffey** [comment]
@beaquant you're right, it _could_ be deleted, but it's common practice to check this file in, so that vgo compiler can give us reproducible builds! 

Check out [this section](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file) in the vgo docs for more info.
