### ISSUE TITLE
support trading record of database

### ISSUE THREAD

**Issue by beaquant** [sdcoffey/techan#4]
what's a wonderful project! It's great!
can it support load trading recorde data from database/log file and save trading record data to database/log file? then analysis this offline data satisfied.

**Comment by sdcoffey** [comment]
Hey @beaquant! Thanks for the feedback. Cool idea - I think it might be outside the scope of this project, since there are a ton of ways you might want to serialize records to log file, to a database, etc. All the fields are public, so you could pretty easily write your own serializer to write trades in your trading record to a file, and then deserialize them and read them back into a new `TradingRecord` later. 

If you disagree, feel free to send me a PR!

**Comment by beaquant** [comment]
thanks for reply. understand and agree. create a techan mate for more extend functions 🔢
